# Generated by Django 4.2.7 on 2023-11-18 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=512)),
                ('difficulty', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('image_id', models.CharField(max_length=128)),
                ('ingredients', models.ManyToManyField(to='api.ingredient')),
            ],
        ),
    ]
