# Generated by Django 4.2.7 on 2023-11-18 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_recipe_ingredients'),
        ('api', '0002_userfeedback'),
    ]

    operations = [
    ]
